services:
  traefik:
    image: "traefik:v2.8"
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.flamingos.acme.tlschallenge=true"
      - "--certificatesresolvers.flamingos.acme.email=leo@flamingos.zip"
      - "--certificatesresolvers.flamingos.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "443:443"
    volumes:
      - "acme:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_INCLUDE_RESTARTING: true

  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: always
    volumes:
      - wakapi-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wakapi.rule=Host(`flamingos.zip`) && PathPrefix(`/waka`)"
      - "traefik.http.routers.wakapi.entrypoints=websecure"
      - "traefik.http.routers.wakapi.tls.certresolver=flamingos"
    environment:
      WAKAPI_PASSWORD_SALT: "IVFONzh7Vk55l1TJOzzd2zPrwLtiYw0i"
      ENVIRONMENT: "prod"
      WAKAPI_BASE_PATH: "/waka"

volumes:
  acme:
  wakapi-data:
