services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - acme:/etc/nginx/certs:ro
  watchtower:
    image: containrrr/watchtower
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_INCLUDE_RESTARTING: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    volumes:
      - wakapi-data:/data
    environment:
      WAKAPI_PASSWORD_SALT: "IVFONzh7Vk55l1TJOzzd2zPrwLtiYw0i"
      ENVIRONMENT: "prod"
      VIRTUAL_HOST: "flamingos.zip"
      VIRTUAL_PORT: "3000"
      VIRTUAL_PATH: "/waka"
      VIRTUAL_DEST: "/"

volumes:
  acme:
  wakapi-data:
