name: Deploy
on:
  push:
    branches: [main]
    paths:
      - "infra/docker-compose.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d --remove-orphans
      - run: docker system prune --all --force
