name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          commits_authoring: levimanga@gmail.com, chaoky, lordie
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_ignored: javascript, AL, Berry, Arc
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 180
          plugin_languages_aliases: RenderScript:Rust # temp solution until Rust as RenderScript bug is fixed
          repositories_affiliations: owner, collaborator, organization_member
          debug: yes

